name: superboard_flutterflow
description: Unified FlutterFlow actions, experiences, purchases, and support for SuperBoard.
version: 3.0.0
publish_to: none

environment:
  sdk: ^3.9.2
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ">=9.2.2 <11.0.0"
  http: ">=1.2.0 <2.0.0"
  superboard_flutter:
    path: ../flutter
  url_launcher: ">=6.3.1 <7.0.0"
  web_socket_channel: ">=3.0.1 <4.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
